### ISSUE TITLE
External clock reference power limit

### ISSUE THREAD

**Issue by Spaqin** [sinara-hw/Kasli#100]
This issue is also on Kasli-SOC as it shares most of the design.

The Kasli wiki mentions quite explicitly:
> 1 SMA to the clock recovery and clock distribution chip used as RTIO reference clock input in master/stand-alone mode (10 dBm sine/square max)

10dBm would mean 2Vp-p w/ 50ohm impedance (and that is doubled by the transformer at the SMA input).

That clock input goes further into the FPGA, to LVDS_25 input (pins U20/V20), where Xilinx specifies the maximum differential input voltage at 600mV (both on Artix and Zynq):
![image](https://user-images.githubusercontent.com/1278433/180911953-e1fc9390-fcf8-4ee7-b760-3df322804882.png)

We found this discrepancy while trying to connect Clocker output to Kasli clock input. Since Clocker output is 800mVp-p with 50ohm impedance, we thought it could cause damage to the FPGA.

In Kasli 1.1 the external clock went directly to Si5324, but in 2.0 (and SoC) it is routed through the FPGA - possibly explaining the rather high signal limit in the wiki.

Is there something we're missing or are the specifications in the wiki wrong?

**Comment by marmeladapk** [comment]
It was not updated for v2. I'll update the wiki and add a note to
schematics (#83).

wt., 26 lip 2022, 04:38 użytkownik Spaqin ***@***.***>
napisał:

**Comment by sbourdeauducq** [comment]
This means using Clocker as clock source requires an attenuator.

**Comment by hartytp** [comment]
> 10dBm would mean 2Vp-p w/ 50ohm impedance (and that is doubled by the transformer at the SMA input).

Checking we're on the same page, but the 2:1 transformer is a sqrt(2) step up on the voltage, not a factor of 2. Or, is that what you meant?

**Comment by hartytp** [comment]
> We found this discrepancy while trying to connect Clocker output to Kasli clock input. Since Clocker output is 800mVp-p with 50ohm impedance, we thought it could cause damage to the FPGA.

nit pick but for the sake of accuracy...agreed that over-driving an input isn't a good idea, but it's worth noting that (unless I'm mistaken) the numbers you quote there are the recommended operating conditions, not the abs max (no damage) ratings. Usually the damage threshold is quite a bit higher than these numbers.

**Comment by hartytp** [comment]
> This means using Clocker as clock source requires an attenuator.

Throwing a couple of options out there if only to discount them:
(a) on the next hw revision we put a clock buffer in front of the FPGA. This adds a bit of additional robustness at the cost of a small amount of additional power dissipation. Am I right in thinking that if we used a 1:2 fanout buffer with the second output connected to CLKIN2 on the 5324 we no longer need to route this signal via the FPGA. May not actually be worth the effort thought...
(b) make a version of clocker which uses a LVDS buffer. Since nothing in Sinara actually uses LVPECL the current design is perhaps not ideally matched. The one caveat here is that the extra uumph is often useful when driving long cable runs which add additional attenuation.

**Comment by gkasprow** [comment]
we may also add a Schottky diode limiter
