### ISSUE TITLE
DC couple the Si5324 into the ADCLK

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#52]
Why AC-couple it? Having a well-defined DC level at the clock buffer input would help to avoid oscillations (the Si5324 can be shutdown from software giving a logic low at the input, so won't oscillate unlike the buffers)

**Comment by marmeladapk** [comment]
@hartytp Currently Si5324 outputs are configured as LVDS on all boards in ARTIQ and LVDS has different common level than LVPECL. 

Also this: 
> The LVPECL outputs are “LVPECL compatible.” No DC biasing circuitry is required to drive a standard LVPECL load.

and this: 
> It is recommended that the outputs be ac coupled to avoid common mode issues.

from Si53xx reference manual doesn't give me much confidence in DC coupling those outputs. I'd leave it as it is unless you have seen problems caused by current coupling.
