### ISSUE TITLE
[RFC] Bigger heat sink

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#7]
- [ ] Use a larger heat sink, maybe with a fan like the one on KC705. Use a clip on heat sink instead of a glue on one.

cf https://github.com/sinara-hw/Kasli/issues/5 and https://github.com/sinara-hw/Zotino/issues/4

**Comment by sbourdeauducq** [comment]
IMO this is the biggest problem with Kasli right now; the current solution of gluing fans and soldering their wires onto other components of the PCB is not nice.

**Comment by sbourdeauducq** [comment]
If 2.0 takes a long time, adding a fan power connector would be a minor change and already a welcome improvement.

**Comment by marmeladapk** [comment]
Since I had to move EEM connectors because of SFP connector I will also move the FPGA away from EEM connectors. This will allow me to place heatsink with fan like this: https://cofan-usa.com/pdf/30-2304_REV01.pdf

I couldn't find any heatsinks with fans for 23mm x 23mm package. 

If you have a tried heatsink with fan please let me know.

**Comment by marmeladapk** [comment]
Closing in favour of #44
